spring:
  data:
    elasticsearch:
      #配置客户端的其他信息
      #properties:
      # 多个节点以,号分割
      cluster-nodes: 192.168.15.130:9300,192.168.15.128:9300
      # 集群名称
      cluster-name: ES
      # 是否启用ElasticSearch存储库 默认为true
      repositories:
        enabled: true


network.host: 0.0.0.0

#因为需要跨服务器访问，所以需要允许外部访问
http.cors.enabled: true
http.cors.allow-origin: "*"
