spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  mail:
    username: sss@qq.com
    password: skskks
    host: smtp.mxhichina.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory


network.host: 0.0.0.0
#因为需要跨服务器访问，所以需要允许外部访问
http.cors.enabled: true
http.cors.allow-origin: "*"
